import { build } from "esbuild";
import { readFile, writeFile, readdir, mkdir } from "node:fs/promises";
import { createHash } from "node:crypto";

// Pin the downloaded data to the exact dictionaries installed by npm ci.
const dictionaryFiles = [];
for (const name of (await readdir("node_modules/kuromoji/dict")).filter(n => n.endsWith(".dat.gz")).sort()) {
  const bytes = await readFile(`node_modules/kuromoji/dict/${name}`);
  dictionaryFiles.push({ name, sha256: createHash("sha256").update(bytes).digest("hex") });
}
await mkdir("src", { recursive: true });
await writeFile("src/dictionary-files.js", `// Generated by scripts/build.mjs from kuromoji@0.1.2.\nexport const dictionaryFiles = ${JSON.stringify(dictionaryFiles, null, 2)};\n`);
const version = JSON.parse(await readFile("package.json", "utf8")).version;
const notices = [];
for (const name of (await readdir("licenses")).sort()) {
  notices.push(`--- ${name} ---\n${(await readFile(`licenses/${name}`, "utf8")).replace(/\r\n/g, "\n")}`);
}
const licenseBanner = `/*!\n${notices.join("\n\n")}\n*/`;
await build({
  entryPoints: ["src/main.js"], outfile: "romaji_lyrics.js", bundle: true,
  platform: "browser", format: "iife", target: "chrome120", minify: false,
  legalComments: "inline", charset: "utf8",
  banner: { js: `// Romaji Lyrics v${version} | MIT | https://github.com/Piyush-Sagar/spicetify-romaji-lyrics\n// Bundled third-party code: see THIRD_PARTY_NOTICES.md and licenses/.\n${licenseBanner}` },
});
console.log(`Built romaji_lyrics.js with ${dictionaryFiles.length} verified dictionary files.`);
